### ISSUE TITLE
Make external reference into a link that opens a new tab

### ISSUE THREAD

**Issue by alvinsw** [Arkisto-Platform/crate-o#13]
An external reference is an object that only has @id, eg `{"@id": "https://example.com/something"}` and there is no entity with the same @id in the crate. If the @id is a valid URL, it should be made into a link that opens a new tab in the web browser. Otherwise, it should enter the create new entity mode.

**Comment by moisbo** [comment]
Done, this will popup a confirm dialog when it cannot find an item... the user can cancel and continue to the site. 
Note: it does not discriminate so anything will be tried in another tab.
